# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  IMAGE_VERSION: '1.8'
  IMAGE_CREATE_DATE: '`date -u +"%Y-%m-%dT%H:%M:%SZ"`'
  IMAGE_SOURCE_REVISION: '`git rev-parse HEAD`'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)