#apiVersion : apps/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbastethellokubernetes 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbastethellokubernetes
  template:
    metadata:
      labels:
        app: lbastethellokubernetes 
    spec:
      containers:
        - name: lbastethellokubernetes 
          image: akscontainerlb.azurecr.io/lbastethellokubernetes
          ports:
          - containerPort: 80
